In [ ]:
# !pip install  sentence-transformers>=3.0.1 gensim>=4.3.2 scikit-learn>=1.5.0 accelerate>0.31.0

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer

model=AutoModelForCausalLM.from_pretrained("microsoft/Phi-3-mini-4k-instruct",
                                           device_map="cuda",
                                           torch_dtype="auto",
                                           trust_remote_code=True,)

tokenizer=AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
prompt="Write an email apologizing to Sarah for the tragic gardening. Explain how it happend. <|assistant|>"
input_ids=tokenizer(prompt,return_tensors="pt").input_ids.to("cuda")

generation_output=model.generate(
    input_ids=input_ids,
    max_new_tokens=200, # Increased max_new_tokens for a longer response
    use_cache=False

)

print(tokenizer.decode(generation_output[0]))

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


Write an email apologizing to Sarah for the tragic gardening. Explain how it happend. <|assistant|> Subject: Sincere Apologies for the Gardening Incident


Dear Sarah,


I hope this message finds you well. I am writing to express my deepest apologies for the unfortunate incident that occurred in your garden yesterday. It was a tragic event that I never intended, and I am truly sorry for the distress it has caused you.


The incident happened when I was attempting to help you with the new irrigation system you had installed. Unfortunately, due to a miscalculation on my part, the system malfunctioned and caused a flood that damaged several of your plants and the garden's layout. I understand that this was a significant setback for you, and I am genuinely remorseful for my role in this.


Please know that I am taking full responsibility for the mishap. I have already contacted a professional gardener to assess the damage and discuss


In [ ]:
print(input_ids)

tensor([[14350,   385,  4876, 27746,  5281,   304, 19235,   363,   278, 25305,
           293, 16423,   292, 29889, 12027,  7420,   920,   372,  2250,   355,
         29889, 29871, 32001]], device='cuda:0')


In [ ]:
for id in input_ids[0]:
  print(tokenizer.decode(id))

 Legion
 d
 weapon
 taxis
 recognize
 use
 conscience
 night
 set
 Bosnia
es
 Hitler
 five
 JFK
UB
 gifts
 child
 great
 Jackson
 added
 JFK
 Terra
hist


In [ ]:
generation_output

tensor([[14350,   385,  4876, 27746,  5281,   304, 19235,   363,   278, 25305,
           293, 16423,   292, 29889, 12027,  7420,   920,   372,  2250,   355,
         29889, 29871, 32001,  3323,   622, 29901,   317,  3742,   406,  6225,
         11763,   363,   278, 19906,   292,  9266,  1693,    13,    13,    13,
         29928,   799, 19235, 29892,    13,    13,    13, 29902,  4966,   445,
          2643, 14061,   366,  1532, 29889,   306,   626,  5007,   304,  4653,
           590,  6483,   342,  3095, 11763,   363,   278,   443,  6477,   403,
         15134,   393, 10761,   297,   596, 16423, 22600, 29889,   739,   471,
           263, 25305,   293,  1741,   393,   306,  2360,  9146, 29892,   322,
           306,   626, 19781,  7423,   363,   278,  1320,  1253,   372,   756,
          8581,   366, 29889,    13,    13,    13,  1576, 15134,  9559,   746,
           306,   471, 15661,   304,  1371,   366,   411,   278,   716,  3805,
          8966,   362,  1788,   366,   750,  5130, 2

In [ ]:
print(tokenizer.decode(3323))
print(tokenizer.decode(622))
print(tokenizer.decode([3323, 622]))
print(tokenizer.decode(29901))

 Sw
 Facebook
 Sw Facebook
 emit


In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer
colors_list = [
    '102;194;165', '252;141;98', '141;160;203',
    '231;138;195', '166;216;84', '255;217;47'
]

def show_tokens(sentence, tokenizer_name):
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
    token_ids = tokenizer(sentence).input_ids
    for idx, t in enumerate(token_ids):
        print(
            f'\x1b[0;30;48;2;{colors_list[idx % len(colors_list)]}m' +
            tokenizer.decode(t) +
            '\x1b[0m',
            end=' '
        )


In [ ]:
text = """
English and CAPITALIZATION
🎵 鸟
show_tokens False None elif == >= else: two tabs:"    " Three tabs: "       "
12.0*50=600
"""

In [ ]:
show_tokens(text, "bert-base-uncased")

[CLS] english and capital ##ization [UNK] [UNK] show _ token ##s false none eli ##f = = > = else : two tab ##s : " " three tab ##s : " " 12 . 0 * 50 = 600 [SEP] 

In [ ]:
show_tokens(text, "bert-base-cased")

[CLS] English and CA ##PI ##TA ##L ##I ##Z ##AT ##ION [UNK] [UNK] show _ token ##s F ##als ##e None el ##if = = > = else : two ta ##bs : " " Three ta ##bs : " " 12 . 0 * 50 = 600 [SEP] 

In [ ]:
show_tokens(text, "gpt2")


 English  and  CAP ITAL IZ ATION 
 � � �  � � � 
 show _ t ok ens  False  None  el if  ==  >=  else :  two  tabs :"        "  Three  tabs :  "              " 
 12 . 0 * 50 = 600 
 

In [ ]:
show_tokens(text, "google/flan-t5-small")

English and CA PI TAL IZ ATION  <unk>  <unk> show _ to ken s Fal s e None  e l if = = > = else : two tab s : " " Three tab s : " " 12. 0 * 50 = 600  </s> 

In [ ]:
# The official is `tiktoken` but this the same tokenizer on the HF platform
show_tokens(text, "Xenova/gpt-4")


 English  and  CAPITAL IZATION 
 � � �  � � � 
 show _tokens  False  None  elif  ==  >=  else :  two  tabs :"      "  Three  tabs :  "         "
 12 . 0 * 50 = 600 
 

In [ ]:
# You need to request access before being able to use this tokenizer
show_tokens(text, "bigcode/starcoder2-15b")


 English  and  CAPITAL IZATION 
 � � �   � � 
 show _ tokens  False  None  elif  ==  >=  else :  two  tabs :"      "  Three  tabs :  "         " 
 1 2 . 0 * 5 0 = 6 0 0 
 

In [ ]:
show_tokens(text, "facebook/galactica-1.3b")


 English  and  CAP ITAL IZATION 
 � � � �  � � � 
 show _ tokens  False  None  elif   ==   > =  else :  two  t abs : "      "  Three  t abs :   "         " 
 1 2 . 0 * 5 0 = 6 0 0 
 

In [ ]:
show_tokens(text, "microsoft/Phi-3-mini-4k-instruct")

 
 English and C AP IT AL IZ ATION 
 � � � �  � � � 
 show _ to kens False None elif == >= else : two tabs :"    " Three tabs : "       " 
 1 2 . 0 * 5 0 = 6 0 0 
 

Contextualized Word Embeddings From a Language Model(like BERT)

In [ ]:
from transformers import AutoModel, AutoTokenizer
tokenizer=AutoTokenizer.from_pretrained("microsoft/deberta-base")
model=AutoModel.from_pretrained("microsoft/deberta-v3-xsmall")
tokens=tokenizer('Hello World',return_tensors='pt')
output=model(**tokens)[0]

In [ ]:
print(output)

tensor([[[-3.2520,  0.1818, -0.1254,  ..., -0.0502, -0.2334,  0.8897],
         [-0.4673,  0.1730, -0.0206,  ..., -0.5289,  0.7303,  2.1177],
         [-0.4950,  0.0564,  0.2842,  ...,  1.0543, -0.1747,  1.3793],
         [-2.9601,  0.2129, -0.1138,  ...,  0.1518, -0.2094,  1.0494]]],
       grad_fn=<NativeLayerNormBackward0>)


In [ ]:
output.shape

torch.Size([1, 4, 384])

In [ ]:
for token in tokens['input_ids'][0]:
  print(tokenizer.decode(token))

[CLS]
Hello
 World
[SEP]


In [ ]:
output

tensor([[[-3.2520,  0.1818, -0.1254,  ..., -0.0502, -0.2334,  0.8897],
         [-0.4673,  0.1730, -0.0206,  ..., -0.5289,  0.7303,  2.1177],
         [-0.4950,  0.0564,  0.2842,  ...,  1.0543, -0.1747,  1.3793],
         [-2.9601,  0.2129, -0.1138,  ...,  0.1518, -0.2094,  1.0494]]],
       grad_fn=<NativeLayerNormBackward0>)

Text Embeddings (For Sentences and Whole Documents)

In [ ]:
from sentence_transformers import SentenceTransformer

model=SentenceTransformer('sentence-transformers/all-mpnet-base-v2')
vector=model.encode("Best movie ever")

In [ ]:
vector.shape

(768,)

Word embeddings beyond LLMs

In [ ]:
import gensim.downloader as api

model=api.load("glove-wiki-gigaword-50")

[==================================================] 100.0% 66.0/66.0MB downloaded


In [ ]:
model.most_similar([model['king']],topn=11)

[('king', 1.0000001192092896),
 ('prince', 0.8236179351806641),
 ('queen', 0.7839043140411377),
 ('ii', 0.7746230363845825),
 ('emperor', 0.7736247777938843),
 ('son', 0.766719400882721),
 ('uncle', 0.7627150416374207),
 ('kingdom', 0.7542161345481873),
 ('throne', 0.7539914846420288),
 ('brother', 0.7492411136627197),
 ('ruler', 0.7434253692626953)]

Recommending songs  by embeddings


In [ ]:
import pandas as pd
from urllib import request

# Get the playlist dataset file
data = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/train.txt')

# Parse the playlist dataset file. Skip the first two lines as
# they only contain metadata
lines = data.read().decode("utf-8").split('\n')[2:]

# Remove playlists with only one song
playlists = [s.rstrip().split() for s in lines if len(s.split()) > 1]

# Load song metadata
songs_file = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/song_hash.txt')
songs_file = songs_file.read().decode("utf-8").split('\n')
songs = [s.rstrip().split('\t') for s in songs_file]
songs_df = pd.DataFrame(data=songs, columns = ['id', 'title', 'artist'])
songs_df = songs_df.set_index('id')

In [ ]:
print( 'Playlist #1:\n ', playlists[0], '\n')
print( 'Playlist #2:\n ', playlists[1])

Playlist #1:
  ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '2', '42', '43', '44', '45', '46', '47', '48', '20', '49', '8', '50', '51', '52', '53', '54', '55', '56', '57', '25', '58', '59', '60', '61', '62', '3', '63', '64', '65', '66', '46', '47', '67', '2', '48', '68', '69', '70', '57', '50', '71', '72', '53', '73', '25', '74', '59', '20', '46', '75', '76', '77', '59', '20', '43'] 

Playlist #2:
  ['78', '79', '80', '3', '62', '81', '14', '82', '48', '83', '84', '17', '85', '86', '87', '88', '74', '89', '90', '91', '4', '73', '62', '92', '17', '53', '59', '93', '94', '51', '50', '27', '95', '48', '96', '97', '98', '99', '100', '57', '101', '102', '25', '103', '3', '104', '105', '106', '107', '47', '108', '109', '110', '111', '112', '113', '25', '63', '62', '114', '115', '84', '116', '117',

In [ ]:
from gensim.models import Word2Vec
model=Word2Vec(playlists,vector_size=32,window=20,negative=50,min_count=1,workers=4)

In [ ]:
song_id=2172

model.wv.most_similar(positive=str(song_id))

[('6624', 0.9981429576873779),
 ('2976', 0.9979757070541382),
 ('2640', 0.9977650046348572),
 ('2849', 0.9977474212646484),
 ('10077', 0.9971644282341003),
 ('2881', 0.9971338510513306),
 ('3167', 0.9970992803573608),
 ('5549', 0.9966198801994324),
 ('3136', 0.9965690970420837),
 ('3094', 0.996370255947113)]

In [ ]:
print(songs_df.iloc[2172])

title     Fade To Black
artist        Metallica
Name: 2172 , dtype: object


In [ ]:
import numpy as np

def print_recommendations(song_id):
    similar_songs = np.array(
        model.wv.most_similar(positive=str(song_id),topn=5)
    )[:,0]
    return  songs_df.iloc[similar_songs]

# Extract recommendations
print_recommendations(2172)

title         artist
id                                            
6624    Everybody Wants Some!!!      Van Halen
2976               I Don't Know  Ozzy Osbourne
2640              Red Barchetta           Rush
2849           Run To The Hills    Iron Maiden
10077           Road To Nowhere  Ozzy Osbourne

In [ ]:
print_recommendations(2172)

title         artist
id                                            
6624    Everybody Wants Some!!!      Van Halen
2976               I Don't Know  Ozzy Osbourne
2640              Red Barchetta           Rush
2849           Run To The Hills    Iron Maiden
10077           Road To Nowhere  Ozzy Osbourne